MairieDelmas.Gestion.EMP/Controllers/CongesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MairieDelmas.Gestion.EMP.Data;
using MairieDelmas.Gestion.EMP.Models.Conge;

namespace MairieDelmas.Gestion.EMP.Controllers
{
    public class CongesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CongesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Conges1
        public async Task<IActionResult> Index()
        {
            return View(await _context.Conge.ToListAsync());
        }

        // GET: Conges1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conge = await _context.Conge
                .FirstOrDefaultAsync(m => m.CongeId == id);
            if (conge == null)
            {
                return NotFound();
            }

            return View(conge);
        }

        // GET: Conges1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Conges1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CongeId,EmployeId,TypeConge,DebutConge,FinConge,ReprendreService,Observation,User,Nom,Prenom,Emploi,Service,NifCin")] Conge conge)
        {
            if (ModelState.IsValid)
            {

                _context.Add(conge);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(conge);
        }

        // GET: Conges1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conge = await _context.Conge.FindAsync(id);
            if (conge == null)
            {
                return NotFound();
            }
            return View(conge);
        }

        // POST: Conges1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CongeId,TypeConge,DebutConge,FinConge,ReprendreService,Observation,EmployeId,User,Nom,Prenom,Emploi,Service,NifCin")] Conge conge)
        {
            if (id != conge.CongeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(conge);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CongeExists(conge.CongeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(conge);
        }

        // GET: Conges1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conge = await _context.Conge
                .FirstOrDefaultAsync(m => m.CongeId == id);
            if (conge == null)
            {
                return NotFound();
            }

            return View(conge);
        }

        // POST: Conges1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var conge = await _context.Conge.FindAsync(id);
            _context.Conge.Remove(conge);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CongeExists(int id)
        {
            return _context.Conge.Any(e => e.CongeId == id);
        }



       
        public async Task<IActionResult> ListeDesEmployesEnConge()
        {

            
            var Cong = from con in _context.Conge
                       where  con.FinConge.Date<=DateTime.Today.Date orderby con.DebutConge descending
                       select con;
            //if (!String.IsNullOrEmpty(recherche))
            //{
            //    Empl = Empl.Where(e => e.Emploi.Contains(recherche) || e.Service.Contains(recherche) || e.Nom.Contains(recherche) || e.Prenom.Contains(recherche));
            //}


            //ViewBag.MaxStorage = Convert.ToInt32((from s in db.storage
            //                                      where s.ID == id
            //                                      select s.AdditionalStorageMax).FirstOrDefault());

            return View(await Cong.ToListAsync());
        }

        public async Task<IActionResult> FueilleDeConge(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var conge = await _context.Conge.FindAsync(id);
            if (conge == null)
            {
                return NotFound();
            }
            return View(conge);
        }





















        //public async Task<IActionResult> CongePourAnneEnCour(string recherche, DateTime date)
        //{

        //    var Cong = from con in _context.Conge
        //               where con.FinConge.Date <= DateTime.Today.Date
        //               select con;
        //    if (!String.IsNullOrEmpty(recherche))
        //    {
        //        Cong = Cong.Where((e => e.Nom.Contains(recherche) || e.Prenom.Contains(recherche) && e.DebutCongeContains(recherche) || e.Prenom.Contains(recherche));
        //    }
        //    return View(await Cong.ToListAsync());

        //}
    }
}

//public IEnumerable<object> Paging(int page)
//{
//    int t = (page - 1) * 10;
//    DB db = new DB();

//    //var q = db.Books.Skip(t).Take(10).ToList();

//    var q = (from i in db.Books
//             select new
//             {
//                 i.id,
//                 i.BookName,
//                 i.Writer,
//                 i.BookcategFK.BookCategori,
//                 i.inventory,
//                 i.BannerImage,

//             }
//             ).Skip(t).Take(10).ToList();

//    return q;
//}

MairieDelmas.Gestion.EMP/Controllers/PostesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MairieDelmas.Gestion.EMP.Data;
using MairieDelmas.Gestion.EMP.Models.Poste;

namespace MairieDelmas.Gestion.EMP.Controllers
{
    public class PostesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Postes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Poste.ToListAsync());
        }

        // GET: Postes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poste = await _context.Poste
                .FirstOrDefaultAsync(m => m.PosteId == id);
            if (poste == null)
            {
                return NotFound();
            }

            return View(poste);
        }

        // GET: Postes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Postes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PosteId,NomPoste,User")] Poste poste)
        {
            if (ModelState.IsValid)
            {
                _context.Add(poste);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(poste);
        }

        // GET: Postes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poste = await _context.Poste.FindAsync(id);
            if (poste == null)
            {
                return NotFound();
            }
            return View(poste);
        }

        // POST: Postes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PosteId,NomPoste,User")] Poste poste)
        {
            if (id != poste.PosteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(poste);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PosteExists(poste.PosteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(poste);
        }

        // GET: Postes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var poste = await _context.Poste
                .FirstOrDefaultAsync(m => m.PosteId == id);
            if (poste == null)
            {
                return NotFound();
            }

            return View(poste);
        }

        // POST: Postes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var poste = await _context.Poste.FindAsync(id);
            _context.Poste.Remove(poste);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PosteExists(int id)
        {
            return _context.Poste.Any(e => e.PosteId == id);
        }
    }
}

MairieDelmas.Gestion.EMP/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MairieDelmas.Gestion.EMP.Data;
using MairieDelmas.Gestion.EMP.Models.Service;

namespace MairieDelmas.Gestion.EMP.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ServicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Services
        public async Task<IActionResult> Index()
        {
            return View(await _context.Service.ToListAsync());
        }

        // GET: Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Service
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // GET: Services/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ServiceId,NomService,User")] Service service)
        {
            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Service.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ServiceId,NomService,User")] Service service)
        {
            if (id != service.ServiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.ServiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Service
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var service = await _context.Service.FindAsync(id);
            _context.Service.Remove(service);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(int id)
        {
            return _context.Service.Any(e => e.ServiceId == id);
        }
    }
}

MairieDelmas.Gestion.EMP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MairieDelmas.Gestion.EMP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MairieDelmas.Gestion.EMP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_LoginPartial" />

                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark  "  asp-area="" asp-controller="Employes" asp-action="Recherche">Employe</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Employes" asp-action="ListeEmployeEligibleConge">Conge</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Corespondances" asp-action="Create">Corespondances</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Doleances" asp-action="Create">Doleances</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
    </header>*@
    @if (SignInManager.IsSignedIn(User))
    {
    <ul class="nav nav-tabs">

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index"> <img class="navbar-brand" src="~/MD logo png copy.png" width="20" alt="Alternate Text" />SOftMED |</a>

        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Connection</a>
            <ul class="dropdown-menu">
                <partial name="_LoginPartial" />
            </ul>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Employes</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-controller="Employes" asp-action="Create">Enregistrer</a></li>
                <li><a class="dropdown-item" asp-controller="Employes" asp-action="RechercheToutEmploye">Recherche Complet</a></li>
                <li><a class="dropdown-item" asp-controller="Employes" asp-action="Recherche">Rechecher Personaliser</a></li>
                @*<li><a class="dropdown-item" asp-controller="Employes" asp-action="RechercheEmployeActif">Rechercher Info Complementaires</a></li>
                <li><a class="dropdown-item" asp-controller="Employes" asp-action="AutreInformation">Rechercher Autre Informations</a></li>
                <li><a class="dropdown-item" asp-controller="Employes" asp-action="RechercheDocument">Rechercher de Document </a></li>
                <li><a class="dropdown-item" asp-controller="Employes" asp-action="ListeEmployeInactif">Employes Inactifs</a></li>*@
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Separated link</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Conge</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-controller="Employes" asp-action="ListeEmployeEligibleConge">Effectuer un Conge</a></li>
                <li><a class="dropdown-item" asp-controller="Conges" asp-action="Index"> Modifier un Conge</a></li>
                <li><a class="dropdown-item" asp-controller="Conges" asp-action="ListeDesEmployesEnConge">Liste Employe en Conge</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Separated link</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Corespondances</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-controller="Corespondances" asp-action="Create">Enregistrer</a></li>
                <li><a class="dropdown-item" asp-controller="Corespondances" asp-action="RechercheCorespondanceSuiviNom">Rechercher</a></li>
                <li><a class="dropdown-item" asp-controller="Corespondances" asp-action="ListeCorespondanceNonSuivie">Non Suivie</a></li>
                @*<li><a class="dropdown-item" asp-controller="" asp-action="">Something else here</a></li>*@
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-controller="Corespondances" asp-action="Index">Lister </a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Doleances</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-controller="Doleances" asp-action="Create">Enregistrer</a></li>
                <li><a class="dropdown-item" asp-controller="Doleances" asp-action="RechercheDoloeance">Rechercher </a></li>
                @*<li><a class="dropdown-item" href="#">Something else here</a></li>*@
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-controller="Doleances" asp-action="Index">Lister</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Parametres</a>
            <ul class="dropdown-menu">
                @*<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>*@

                <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Nouveau Utilisateur</a></li>
                <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">Modifier User </a></li>
                <li><a class="dropdown-item" asp-controller="Postes" asp-action="Create">Nouveau Poste</a></li>
                <li><a class="dropdown-item" asp-controller="Services" asp-action="Create">Nouvau Service</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-controller="Doleances" asp-action="Index">Lister</a></li>
            </ul>
        </li>

    </ul>
    }

    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white">
        <div class="container-fluid bg-primary">
            &copy; 2022 - MairieDelmas.Gestion.EMP , Logiciel de Gestion des Employes
            @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>