MairieDelmas.Gestion.EMP/Models/Promotion/Promotion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MairieDelmas.Gestion.EMP.Models.Promotion
{
    public class Promotion
    {
        public int PromotionId { get; set; }
        public string  Nom { get; set; }
        public string  Prenom { get; set; }
        public string  NifCIn { get; set; }
        public string  AncienPoste { get; set; }
        public string  AncienService { get; set; }
        [Required]
        public string NouveauPoste { get; set; }
        [Required]
        public string  NouveauService { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime DatePromotion { get; set; }
        public string  RemarquePromotion { get; set; }
        public string User { get; set; }
        [ForeignKey("EmployeId")]
        public int EmployeId { get; set; }
    }
}

MairieDelmas.Gestion.EMP/Controllers/EmployesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MairieDelmas.Gestion.EMP.Data;
using MairieDelmas.Gestion.EMP.Models.Employe;
using Microsoft.AspNetCore.Authorization;
using MairieDelmas.Gestion.EMP.Models.Conge;

namespace MairieDelmas.Gestion.EMP.Controllers
{
    public class EmployesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employes
      //  [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employe.ToListAsync());
        }
        //Random co = new Random();
        //string code = string.Format("EMP-MD-{0}{1}{2}", co.Next(0, 9), co.Next(0, 9), co.Next(1, 999), DateTime.Now.Millisecond);

        // GET: Employes/Details/5
       // [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employe = await _context.Employe
                .FirstOrDefaultAsync(m => m.EmployeId == id);
            if (employe == null)
            {
                return NotFound();
            }

            return View(employe);
        }

        // GET: Employes/Create
     //   [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeId,TypeContrat,Nom,Prenom,DateNaissance,LieudeNaissance,Nationalite,PaysdeNaissance,Adresse,SituationFamiliale,NombrePersaCharge,NombreEnfants,NIFCIN,Emploi,Service,Cadre,Telephone,Portable,Email,PersonneAPrevenir,PortablePersonneAPrevenir,Liens,CarteIdentification,CV,Photo,PermisConduire,Allergies,Gs,Maladies,Remarques,DatederniereVisite,DateEntreaLaMairie,CompteBancaireBNC,AutreFormation,EtudeEncour,Etat,User,DatechangementEtat,Remarque")] Employe employe)
        {
            Random co = new Random();
            string code = string.Format("EMP-MD-{0}{1}{2}", co.Next(0, 9), co.Next(0, 99), co.Next(1, 999), DateTime.Now.Millisecond);

            if (ModelState.IsValid)
            {
                
                employe .CodeEmp = code;
                employe.Etat = "Actif";
                _context.Add(employe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Recherche));
            }
            return View(employe);
        }
     //   [Authorize]
        // GET: Employes/Edit/5
        // [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employe = await _context.Employe.FindAsync(id);
            if (employe == null)
            {
                return NotFound();
            }
            return View(employe);
        }

        // POST: Employes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
     //   [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmployeId,CodeEmp,TypeContrat,Nom,Prenom,DateNaissance,LieudeNaissance,Nationalite,PaysdeNaissance,Adresse,SituationFamiliale,NombrePersaCharge,NombreEnfants,NIFCIN,Emploi,Service,Cadre,Telephone,Portable,Email,PersonneAPrevenir,PortablePersonneAPrevenir,Liens,CarteIdentification,CV,Photo,PermisConduire,Allergies,Gs,Maladies,Remarques,DatederniereVisite,DateEntreaLaMairie,CompteBancaireBNC,AutreFormation,EtudeEncour,Etat,User,DatechangementEtat,Remarque")] Employe employe)
        {
            if (id != employe.EmployeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeExists(employe.EmployeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Recherche));
            }
            return View(employe);

        }
      //  [Authorize]
        // GET: Employes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employe = await _context.Employe
                .FirstOrDefaultAsync(m => m.EmployeId == id);
            if (employe == null)
            {
                return NotFound();
            }

            return View(employe);
        }

        // POST: Employes/Delete/5
       // [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employe = await _context.Employe.FindAsync(id);
            _context.Employe.Remove(employe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Recherche));
        }

        private bool EmployeExists(int id)
        {
            return _context.Employe.Any(e => e.EmployeId == id);
        }

      // [Authorize]
        [HttpGet]
        public async Task<IActionResult> Recherche(string recherche)
        {
            var Empl = from Emp in _context.Employe
                       where Emp.Etat == "Actif"
                       select Emp;
            ViewBag.MaxStorage = Convert.ToInt32((from comp in _context.Employe
                                                  where comp.Etat == "Actif"
                                                  select comp).Count());
            if (!String.IsNullOrEmpty(recherche))
            {
                Empl = Empl.Where(e => e.Nom!.Contains(recherche)||e.Prenom!.Contains(recherche) );
            }


            return View(await Empl.ToListAsync());

        }
       // [Authorize]
        [HttpGet]
        public async Task<IActionResult> RechercheDocument(string recherche)
        {
            var Empl = from Emp in _context.Employe
                       where Emp.Etat == "Actif"

                       select Emp;
            if (!String.IsNullOrEmpty(recherche))
            {
                Empl = Empl.Where(e => e.Nom.Contains(recherche) || e.Prenom.Contains(recherche)||e.NIFCIN.Contains(recherche));
            }
         

            return View(await Empl.ToListAsync());

        }



      //  [Authorize]
        public  async   Task<IActionResult> CongeEmp(int? id )
        {
           
            if (id == null)
            {
                return NotFound();
            }
            Employe employe = await _context.Employe
                  .FirstOrDefaultAsync(m => m.EmployeId == id);
            ViewBag.EmployeId = id;
            ViewData["Employe"] = employe;



            return View();
        }

       // [Authorize]
        public async Task<IActionResult> RechercheEmployeActif(string recherche)
        {
            var Empl = from Emp in _context.Employe
                       where Emp.Etat == "Actif"
                       select Emp;
            
            if (!String.IsNullOrEmpty(recherche))
            {
                Empl = Empl.Where(e => e.Emploi.Contains(recherche) ||e.Service.Contains(recherche) ||e.Nom.Contains(recherche) ||e.Prenom.Contains(recherche));
            }


            return View(await Empl.ToListAsync());

        }
       // [Authorize]
        public async Task<IActionResult> AutreInformation (string recherche)
        {
            var Empl = from Emp in _context.Employe
                   where    Emp.Etat == "Actif"
                       select Emp ;
            if (!String.IsNullOrEmpty(recherche))
            {
                Empl = Empl.Where(e => e.Allergies.Contains(recherche) ||e.Nom.Contains(recherche)||e.Prenom.Contains(recherche)||e.CompteBancaireBNC.Contains (recherche ));
            }


            return View(await Empl.ToListAsync());

        }
      //  [Authorize]
        public async Task<IActionResult> ListerNom()
        {
            var Empl = from Emp in _context.Employe
                       where Emp.Etat == "Actif"
                       orderby Emp.Nom ascending

                       select Emp;

            return View(await Empl.ToListAsync());
        }

      //  [Authorize]
        public async Task<IActionResult> EnregistrerInfoComplementaire(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var employe = await _context.Employe.FindAsync(id);
            if (employe == null)
            {
                return NotFound();
            }
            
            ViewBag.Poste = from po in _context.Poste

                            select po;
            ViewBag.Service = from se in _context.Service

                              select se;

            return View(employe);
        }
    //    [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]

MairieDelmas.Gestion.EMP/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MairieDelmas.Gestion.EMP.Data;
using MairieDelmas.Gestion.EMP.Models.Promotion;

namespace MairieDelmas.Gestion.EMP.Controllers
{
    public class PromotionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PromotionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Promotions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Promotion.ToListAsync());
        }

        // GET: Promotions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion
                .FirstOrDefaultAsync(m => m.PromotionId == id);
            if (promotion == null)
            {
                return NotFound();
            }

            return View(promotion);
        }

        // GET: Promotions/Create
        public IActionResult Create(int ? id)
        {
            
            return View();
        }

        // POST: Promotions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PromotionId,Nom,Prenom,NifCIn,AncienPoste,AncienService,NouveauPoste,NouveauService,DatePromotion,RemarquePromotion,User,EmployeId")] Promotion promotion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(promotion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ListePromotion));
            }
            return View(promotion);
        }

        // GET: Promotions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion.FindAsync(id);
            if (promotion == null)
            {
                return NotFound();
            }
            return View(promotion);
        }

        // POST: Promotions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PromotionId,Nom,Prenom,NifCIn,AncienPoste,AncienService,NouveauPoste,NouveauService,DatePromotion,RemarquePromotion,User,EmployeId")] Promotion promotion)
        {
            if (id != promotion.PromotionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promotion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromotionExists(promotion.PromotionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(promotion);
        }

        // GET: Promotions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion
                .FirstOrDefaultAsync(m => m.PromotionId == id);
            if (promotion == null)
            {
                return NotFound();
            }

            return View(promotion);
        }

        // POST: Promotions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var promotion = await _context.Promotion.FindAsync(id);
            _context.Promotion.Remove(promotion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PromotionExists(int id)
        {
            return _context.Promotion.Any(e => e.PromotionId == id);
        }

        public async Task<IActionResult> ListePromotion(string recherche)
        {
            var Promot = from prom in _context.Promotion
                         select prom;

            ViewBag.Promotion = Convert.ToInt32((from comp in _context.Promotion

                                                 select comp).Count());


            if (!String.IsNullOrEmpty(recherche))
            {
                Promot = Promot.Where(e => e.Nom.Contains(recherche) || e.Prenom.Contains(recherche) || e.AncienService.Contains(recherche) || e.AncienPoste.Contains(recherche) || e.NifCIn.Contains(recherche) || e.NouveauPoste.Contains(recherche));
            }

            return View(await Promot.ToListAsync());
        }
    }
}

MairieDelmas.Gestion.EMP/Views/Promotions/Create.cshtml
@model MairieDelmas.Gestion.EMP.Models.Promotion.Promotion

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Promotion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NifCIn" class="control-label"></label>
                <input asp-for="NifCIn" class="form-control" />
                <span asp-validation-for="NifCIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AncienPoste" class="control-label"></label>
                <input asp-for="AncienPoste" class="form-control" />
                <span asp-validation-for="AncienPoste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AncienService" class="control-label"></label>
                <input asp-for="AncienService" class="form-control" />
                <span asp-validation-for="AncienService" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NouveauPoste" class="control-label"></label>
                <input asp-for="NouveauPoste" class="form-control" />
                <span asp-validation-for="NouveauPoste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NouveauService" class="control-label"></label>
                <input asp-for="NouveauService" class="form-control" />
                <span asp-validation-for="NouveauService" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePromotion" class="control-label"></label>
                <input asp-for="DatePromotion" class="form-control" />
                <span asp-validation-for="DatePromotion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RemarquePromotion" class="control-label"></label>
                <input asp-for="RemarquePromotion" class="form-control" />
                <span asp-validation-for="RemarquePromotion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User" class="control-label"></label>
                <input asp-for="User" class="form-control" />
                <span asp-validation-for="User" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeId" class="control-label"></label>
                <input asp-for="EmployeId" class="form-control" />
                <span asp-validation-for="EmployeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MairieDelmas.Gestion.EMP/Views/Promotions/Delete.cshtml
@model MairieDelmas.Gestion.EMP.Models.Promotion.Promotion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Promotion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NifCIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NifCIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AncienPoste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AncienPoste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AncienService)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AncienService)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NouveauPoste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NouveauPoste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NouveauService)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NouveauService)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePromotion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePromotion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RemarquePromotion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RemarquePromotion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PromotionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MairieDelmas.Gestion.EMP/Views/Promotions/Details.cshtml
@model MairieDelmas.Gestion.EMP.Models.Promotion.Promotion

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Promotion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NifCIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NifCIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AncienPoste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AncienPoste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AncienService)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AncienService)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NouveauPoste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NouveauPoste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NouveauService)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NouveauService)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatePromotion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatePromotion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RemarquePromotion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RemarquePromotion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PromotionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MairieDelmas.Gestion.EMP/Views/Promotions/ListePromotion.cshtml
@model IEnumerable<MairieDelmas.Gestion.EMP.Models.Promotion.Promotion>

@{
    ViewData["Title"] = "ListePromotion";
}

<div class=" bg-primary text-uppercase text-white shadow">
    <img src="~/MD logo png copy.png" width="60" alt="Alternate Text" />  <h2 class="d-inline">Employes Mairie de Delmas</h2>
</div>


<div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" asp-controller="Employes" asp-action="Recherche">Information Personelles</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-controller="Employes" asp-action="RechercheEmployeActif">Informations Complementaires</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Employes" asp-action="AutreInformation">Autres Informations</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Employes" asp-action="RechercheDocument">Documents de Dossiers</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-controller="Promotions" asp-action="ListePromotion">Promotion <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger text-white"> @ViewBag.Promotion</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Employes" asp-action="ListeEmployeInActif">Changement d'Etat</a>
        </li>
    </ul>
</div>

<div class="row  mt-2">
    <div class="col-md-8 ml-3">
        <form asp-action="ListePromotion" method="get">
            <div class="input-group">
                <input type="text" name="Recherche" class="form-control col-4 pl-4" placeholder="Service , Poste..." />
                <button type="submit" class="btn btn btn-outline-light border-0 " value="Filter"> <img src="~/search.svg" alt="Alternate Text" /></button>
            </div>
        </form>
    </div>

</div>

<fieldset class="border border-primary pt-2 overflow-auto " style="height:450px">
    <legend class="w-auto text-primary">  <a asp-action="Create" class="btn btn-outline-light border-0"><img style="width:40px" src="~/person-plus.svg" alt="Alternate Text" /> </a> </legend>
    <table class="table table-striped  table-sm table-hover">
        <thead class="table-primary text-center">
            <tr style="font-size:small">
                <th>
                    @Html.DisplayNameFor(model => model.Nom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Prenom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NifCIn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AncienPoste)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AncienService)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NouveauPoste)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NouveauService)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DatePromotion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RemarquePromotion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.User)
                </th>
                
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr  class="text-center" style="font-size:small">
                    <td>
                        @Html.DisplayFor(modelItem => item.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prenom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NifCIn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AncienPoste)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AncienService)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NouveauPoste)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NouveauService)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatePromotion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RemarquePromotion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.PromotionId"><img src="~/search.svg" alt="Alternate Text" /></a> 
                        <a asp-action="Details" asp-route-id="@item.PromotionId"><img src="~/eye.svg" alt="Alternate Text" /></a> 
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </fieldset>